---
- hosts: all
  gather_facts: no
  roles:  
          - iis-install
          - iiscrypto-install
        
  vars_prompt:
    - name: behind_elb
      prompt: "\nWill the webserver be behind a load balancer? (y/n)"
      default: "y"
      private: no
